# Generated by Django 6.0.7 on 2026-07-15 09:29

import django.core.validators
import monitor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('check_interval_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('timeout_seconds', models.IntegerField(default=30)),
                ('accepted_status_code', models.JSONField(default=monitor.models.Monitor.default_status_codes)),
                ('consecutive_failures_threshold', models.IntegerField(default=2)),
                ('slow_response_threshold_ms', models.IntegerField(blank=True, null=True)),
                ('http_method', models.CharField(choices=[('HEAD', 'HEAD'), ('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], default='HEAD', max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('send_body_as_json', models.BooleanField(default=False)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic')], default='none', max_length=10)),
                ('auth_username', models.CharField(blank=True, max_length=255)),
                ('auth_password', models.CharField(blank=True, max_length=255)),
                ('follow_redirect', models.BooleanField(default=True)),
                ('ip_version', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('ipv4_priority', 'IPv4 Priority')], default='ipv4_priority', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
