# Generated by Django 6.0.7 on 2026-07-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
