# Generated by Django 6.0.7 on 2026-07-15 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='accepted_status_code',
            new_name='accepted_status_codes',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='follow_redirect',
            new_name='follow_redirects',
        ),
        migrations.AddField(
            model_name='monitor',
            name='has_run_first_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='timeout_seconds',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
