# Generated by Django 6.0.7 on 2026-08-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_rename_accepted_status_code_monitor_accepted_status_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
