# Generated by Django 6.0.7 on 2026-07-20 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0003_rename_accepted_status_code_monitor_accepted_status_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('root_cause', models.CharField(choices=[('connection_timeout', 'Connection Timeout'), ('connection_error', 'Connection Error'), ('http_error', 'HTTP Error'), ('ssl_expired', 'SSL Expired'), ('ssl_error', 'SSL Error'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('suppressed_by_maintenance', models.BooleanField(default=False)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='monitor.monitor')),
            ],
        ),
    ]
