# Generated by Django 6.0.7 on 2026-07-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0003_rename_accepted_status_code_monitor_accepted_status_codes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='monitor.monitor')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['monitor', 'executed_at'], name='check_check_monitor_6afa18_idx')],
            },
        ),
    ]
